# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: push

env:
  DOCKER_USER: ${{ secrets.USER }}
  DOCKER_PASS: ${{ secrets.PASS }}

jobs:
  build-node:
   runs-on: ubuntu-latest
   container: node
   steps:
    - name: Check version node
      run: node --version
    - name: Check version npm
      run: npm --version
    - uses: actions/checkout@v3
    - run: npm test     
    - name: Login to Docker Hub
      if: success()
      uses: docker/login-action@v1
      with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ env.DOCKERHUB_PASS }}
    - name: Build Docker image
      run: |
          docker build -t myapp:latest .
    - name: Push Docker image
      run: |
          docker tag myapp:latest ${{ env.DOCKER_USERNAME }}/myapp:latest
          docker push ${{ env.DOCKER_USERNAME }}/myapp:latest
