# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: push

jobs:
  build-node:
   runs-on: ubuntu-latest
   container: node
   steps:
    - name: Check version node
      run: node --version
    - name: Check version npm
      run: npm --version
    - uses: actions/checkout@v3
    - run: npm test
    - name: Docker Log
      if: success()
      uses: docker/login-action@v1
      with:
          file: ./Docker/Dockerfile
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS}}
    - name: Docker Push
      if: success()
      uses: docker/build-push-action@v4
      with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
