# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: push

jobs:
  build-node:
   runs-on: ubuntu-latest
   container: node
   steps:
    - name: Check version node
      run: node --version
    - name: Check version npm
      run: npm --version
    - uses: actions/checkout@v3
    - run: npm test
    - name: Docker Log and Push container
      if: success()
      uses: docker/login-action@v2
      with:
          username: ${{ secret.USER }}
          password: ${{ secrets.GITHUB_TOKEN }}
          if: success()
          uses: docker/build-push-action@v4
          push: true
          tags: ganon117/app:latest
      
